% Export the proposed case-3 inversion panel with water-line and A1-A3 only.
clear; clc; close all;

rootDir = fileparts(fileparts(mfilename('fullpath')));
caseDir = fullfile(rootDir, 'shice', '3');
outDir = fullfile(caseDir, 'evidence_support');
dataPath = fullfile(outDir, 'case3_proposed_with_evidence_overlay_data.mat');
assert(exist(dataPath, 'file') == 2, 'Missing overlay data: %s', dataPath);
S = load(dataPath);

outPath = fullfile(outDir, 'case3_proposed_with_waterline_A1_A3.emf');
plot_single_panel(S.rhoDisplay, S.climVals, S.waterX, S.waterLine, ...
    S.anomalies, outPath);

fprintf('Saved single proposed evidence panel: %s\n', outPath);


function plot_single_panel(rhoDisplay, climVals, waterX, waterLine, ...
        anomalies, outPath)
    fig = figure('Visible', 'off', 'Color', 'w', ...
        'Units', 'pixels', 'Position', [100, 100, 1120, 680], ...
        'Renderer', 'painters', 'InvertHardcopy', 'off');
    ax = axes('Parent', fig, 'Units', 'normalized', ...
        'Position', [0.105, 0.180, 0.765, 0.720]);
    imagesc(ax, [0, 102], [81, 99], rhoDisplay);
    set(ax, 'YDir', 'normal');
    colormap(ax, jet(256));
    caxis(ax, climVals);
    hold(ax, 'on');
    plot(ax, waterX, waterLine, 'k-', 'LineWidth', 2.4);
    for k = 1:numel(anomalies)
        rectangle(ax, 'Position', anomalies(k).position, ...
            'Curvature', [1, 1], 'EdgeColor', 'k', ...
            'LineStyle', '--', 'LineWidth', 2.2);
        text(ax, anomalies(k).center(1), anomalies(k).center(2), ...
            sprintf('A_%d', k), 'Color', 'w', ...
            'FontName', 'Times New Roman', 'FontWeight', 'bold', ...
            'FontSize', 24, 'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', 'Interpreter', 'tex');
    end
    text(ax, 62, 88.2, 'Water-line', ...
        'FontName', 'Times New Roman', 'FontWeight', 'bold', ...
        'FontSize', 22, 'Color', 'k', 'BackgroundColor', 'w', ...
        'Margin', 1.5);
    hold(ax, 'off');
    set(ax, 'FontName', 'Times New Roman', ...
        'FontWeight', 'bold', 'FontSize', 38, ...
        'LineWidth', 1.8, 'Box', 'on', ...
        'TickDir', 'in', 'Layer', 'top', ...
        'XTick', [40, 80, 102], ...
        'XTickLabel', {'40', '80', '102'}, ...
        'YTick', [81, 85, 89, 93, 97, 99], ...
        'YTickLabel', {'81', '85', '89', '93', '97', '99'});
    xlabel(ax, 'Distance (m)', 'FontName', 'Times New Roman', ...
        'FontWeight', 'bold', 'FontSize', 38);
    ylabel(ax, 'Elevation (m)', 'FontName', 'Times New Roman', ...
        'FontWeight', 'bold', 'FontSize', 38);
    xlim(ax, [0, 102]);
    ylim(ax, [81, 99]);

    cb = colorbar(ax, 'Units', 'normalized', ...
        'Position', [0.895, 0.180, 0.032, 0.720]);
    set(cb, 'FontName', 'Times New Roman', ...
        'FontWeight', 'bold', 'FontSize', 38, ...
        'LineWidth', 1.5, 'TickDirection', 'in');
    title(cb, 'log_{10}(\rho)', 'Interpreter', 'tex', ...
        'FontName', 'Times New Roman', 'FontWeight', 'bold', ...
        'FontSize', 32);
    set(fig, 'PaperPositionMode', 'auto');
    print(fig, outPath, '-dmeta', '-r600');
    close(fig);
end
